# Generated by Django 4.2.3 on 2023-07-13 03:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=200)),
                ('EventDate', models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 12, 48, 579207))),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='static/images')),
                ('EventName', models.TextField(default='all', max_length=200)),
                ('EventDate', models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 12, 48, 579207))),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.galleryheadings')),
            ],
        ),
    ]
