# Generated by Django 4.2.3 on 2023-07-13 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_galleryheadings_eventdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 14, 53, 361344)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 14, 53, 361344)),
        ),
    ]
