# Generated by Django 4.2.3 on 2023-07-13 03:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_galleryheadings_eventdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 20, 15, 854527)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 20, 15, 855557)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.galleryheadings'),
        ),
    ]
