# Generated by Django 4.2.3 on 2023-07-13 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_galleryheadings_eventdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryheadings',
            name='EventDate',
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='heading',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 22, 12, 754496)),
        ),
    ]
