# Generated by Django 4.2.3 on 2023-07-13 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_remove_galleryheadings_eventdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimages',
            name='heading',
        ),
        migrations.AddField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 40, 50, 856776)),
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='heading',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 40, 50, 855620)),
        ),
    ]
