# Generated by Django 4.2.3 on 2023-07-13 04:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_remove_galleryimages_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimages',
            name='Image',
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 42, 37, 894437)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 42, 37, 894437)),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='static/images')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.galleryimages')),
            ],
        ),
    ]
